spin_manifest_version = 2

[application]
authors = ["fl-lutz <florian.lutz@zeiss.com>"]
description = "Forwards request to an input port"
name = "forward"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "forward"

[variables]
forward_port = { required = true }

[component.forward]
source = "target/forward.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["http://localhost:*"]

[component.forward.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]

[component.forward.variables]
forward_port = "{{ forward_port }}"
