spin_manifest_version = 2

[application]
authors = ["fl-lutz <florian.lutz@zeiss.com>"]
description = "An api to test the dotnet aspire framework"
name = "api"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "api"

[component.api]
source = "target/api.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = []

[component.api.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
